name: bluez
version: 5.37-1
icon: icon.png
type: app
summary: Bluetooth tools and daemons
description: "This package contains tools and system daemons for using Bluetooth
devices. BlueZ is the official Linux Bluetooth protocol stack. It is an Open Source
project distributed under GNU General Public License (GPL)."

apps:
  bluetoothctl:
    command: usr/bin/bluetoothctl
    uses: [bluez-client]
  obexctl:
    command: usr/bin/obexctl
    uses: [bluez-client]    
  bluez:
    command: "usr/lib/bluetooth/bluetoothd -E"
    daemon: simple
    uses: [bluez-service]
  obex:
    command: "usr/lib/bluetooth/obexd"
    daemon: simple
    uses: [obex-service]
uses:
  bluez-client:
    type: migration-skill
    caps: [bluez_client]
  bluez-service:
    type: migration-skill
    security-policy:
      apparmor: bluez.apparmor
      seccomp: bluez.seccomp
  obex-service:
    type: migration-skill  
    security-policy:  
      apparmor: obex.apparmor
      seccomp: obex.seccomp

parts:
  bluez:
    plugin: autotools
    source: https://www.kernel.org/pub/linux/bluetooth/bluez-5.37.tar.xz
    configflags:
      - --prefix=/usr
      - --libexec=/usr/lib/
      - --enable-experimental
      - --enable-snappy
      - --enable-threads
      - --disable-cups
      - --disable-monitor
      - --enable-obex
      - --disable-systemd
      - --disable-silent-rules
    build-packages:
      - libical-dev
      - libreadline6-dev    
      - libudev-dev
      - pkg-config
      - quilt
    stage-packages:
      - libglib2.0-dev
      - libdbus-1-dev
      - libical1a 
    filesets:
      libical1a:
        - usr/lib/*/libical*
    snap:
      - usr/lib/bluetooth/bluetoothd
      - usr/lib/bluetooth/obexd
      - usr/bin/bluetoothctl
      - usr/bin/obexctl
      - usr/share/doc/libical1a/copyright
      - $libical1a
  dbus-configuration:
    plugin: copy
    files: 
      conf/bluez-dbus.conf: conf/bluez-dbus.conf
      meta/framework-policy: meta/framework-policy
      copyright: usr/share/doc/bluez/copyright
      doc/overview.md: usr/share/doc/bluez/overview.md
