name: bluez
version: 5.53-1-dev
type: app
summary: Bluetooth tools and daemons
description: |
 This package contains tools and system daemons for using Bluetooth
 devices. BlueZ is the official Linux Bluetooth protocol stack. It
 is an Open Source project distributed under GNU General Public
 License (GPL). See the project homepage for more details:
 https://code.launchpad.net/~snappy-hwe-team/snappy-hwe-snaps/+git/bluez
confinement: strict
grade: stable
base: core20

layout:
  /usr/var/lib/bluetooth:
    symlink: $SNAP_DATA
  /usr/etc/bluetooth:
    symlink: $SNAP_DATA/etc

apps:
  bluetoothctl:
    command: bin/client-wrapper usr/bin/bluetoothctl
    plugs: [client, uhid]
  obexctl:
    command: bin/client-wrapper usr/bin/obexctl
    plugs: [client]
  bluez:
    command: "usr/lib/bluetooth/bluetoothd -E"
    daemon: simple
    slots: [service]
    plugs: [uhid]
  obex:
    command: "usr/lib/bluetooth/obexd"
    daemon: simple
    slots: [service]
  hciconfig:
    command: usr/bin/hciconfig
    plugs: [bluetooth-control]
  hcidump:
    command: usr/bin/hcidump
    plugs: [bluetooth-control, network-control, home]
  hciattach:
    command: usr/bin/hciattach
    plugs: [bluetooth-control]
  btattach:
    command: usr/bin/btattach
    plugs: [bluetooth-control]
  hcitool:
    command: usr/bin/hcitool
    plugs: [bluetooth-control]
  sdptool:
    command: usr/bin/sdptool
    plugs: [client]
  btmon:
    command: usr/bin/btmon
    plugs: [bluetooth-control, network-control, home]
  btmgmt:
    command: usr/bin/btmgmt
    plugs: [bluetooth-control, network-control]
  meshctl:
    command: usr/bin/meshctl
    plugs: [bluetooth-control, network-control]

plugs:
  client:
      interface: bluez
slots:
  service:
      interface: bluez

parts:
  bluez-common:
    plugin: dump
    source: bin/
    organize:
      client-wrapper: bin/client-wrapper
  changelog:
    plugin: nil
    override-build: |
      cp "$SNAPCRAFT_PROJECT_DIR"/ChangeLog "$SNAPCRAFT_PART_INSTALL"
    organize:
      ChangeLog: snap/ChangeLog
  bluez:
    plugin: autotools
    source: https://git.launchpad.net/ubuntu/+source/bluez
    source-type: git
    source-branch: applied/5.53-0ubuntu2
    configflags:
      - --prefix=/usr
      - --libexec=/usr/lib/
      - --enable-experimental
      - --enable-threads
      - --disable-cups
      - --enable-obex
      - --disable-systemd
      - --disable-silent-rules
      - --enable-test
      - --enable-deprecated
      - --enable-mesh
    build-packages:
      - flex
      - bison
      - libdbus-glib-1-dev
      - libglib2.0-dev
      - libcap-ng-dev
      - udev
      - libudev-dev
      - libreadline-dev
      - libical-dev
      - check
    prime:
      - usr/lib/bluetooth/bluetoothd
      - usr/lib/bluetooth/obexd
      - usr/bin/bluetoothctl
      - usr/bin/obexctl
      - usr/bin/hciconfig
      - usr/bin/hcidump
      - usr/bin/hciattach
      - usr/bin/btattach
      - usr/bin/hcitool
      - usr/bin/sdptool
      - usr/bin/btmon
      - usr/bin/btmgmt
      - usr/bin/meshctl
    override-build: |
      git config user.email "snapcraft@canonical.com"
      git config user.name "snapcraft"
      git am "$SNAPCRAFT_PROJECT_DIR"/patch/*
      snapcraftctl build
      cp tools/btmgmt "$SNAPCRAFT_PART_INSTALL"/usr/bin/
      cp tools/obexctl "$SNAPCRAFT_PART_INSTALL"/usr/bin/
      # Run all tests shiped by default
      make check
