name: bluez
version: 5.37-2
type: app
summary: Bluetooth tools and daemons
description: |
 This package contains tools and system daemons for using Bluetooth
 devices. BlueZ is the official Linux Bluetooth protocol stack. It
 is an Open Source project distributed under GNU General Public
 License (GPL). See the project homepage for more details:
 https://code.launchpad.net/~snappy-hwe-team/snappy-hwe-snaps/+git/bluez
confinement: strict
grade: stable

apps:
  bluetoothctl:
    command: usr/bin/bluetoothctl
    plugs: [client]
    aliases:
      - bluetoothctl
  obexctl:
    command: usr/bin/obexctl
    plugs: [client]
    aliases:
      - obexctl
  bluez:
    command: "usr/lib/bluetooth/bluetoothd -E"
    daemon: simple
    slots: [service]
  obex:
    command: "usr/lib/bluetooth/obexd"
    daemon: simple
    slots: [service]
  hciconfig:
    command: usr/bin/hciconfig
    plugs: [bluetooth-control]
    aliases:
      - hciconfig
  hcidump:
    command: usr/bin/hcidump
    plugs: [bluetooth-control]
    aliases:
      - hcidump
  hciattach:
    command: usr/bin/hciattach
    plugs: [bluetooth-control]
    aliases:
      - hciattach
  hcitool:
    command: usr/bin/hcitool
    plugs: [bluetooth-control]
    aliases:
      - hcitool

plugs:
  client:
      interface: bluez
slots:
  service:
      interface: bluez

parts:
  bluez:
    plugin: autotools
    source: https://git.launchpad.net/~snappy-hwe-team/snappy-hwe-snaps/+git/bluez
    source-type: git
    source-branch: bluez/5.37
    configflags:
      - --prefix=/usr
      - --libexec=/usr/lib/
      - --enable-experimental
      - --enable-threads
      - --disable-cups
      - --disable-monitor
      - --enable-obex
      - --disable-systemd
      - --disable-silent-rules
      - --enable-test
    build-packages:
      - libglib2.0-dev
      - libdbus-1-dev
      - libical-dev
      - libreadline6-dev
      - libudev-dev
      - udev
      - pkg-config
    stage-packages:
      - libical1a
    filesets:
      libical1a:
        - usr/lib/*/libical*
    snap:
      - usr/lib/bluetooth/bluetoothd
      - usr/lib/bluetooth/obexd
      - usr/bin/bluetoothctl
      - usr/bin/obexctl
      - usr/bin/hciconfig
      - usr/bin/hcidump
      - usr/bin/hciattach
      - usr/bin/hcitool
      - usr/share/doc/libical1a/copyright
      - $libical1a
    install: |
      # Run all tests shiped by default
      make check

  common:
    plugin: dump
    organize:
      copyright: usr/share/doc/bluez/copyright
      doc/overview.md: usr/share/doc/bluez/overview.md
    prime:
      - usr/share/doc/bluez/copyright
      - usr/share/doc/bluez/overview.md
